import {
	BookOpen,
	Briefcase,
	Building2,
	Code2,
	Cloud,
	Database,
	Factory,
	FlaskConical,
	GitBranch,
	GraduationCap,
	Grid3x3,
	HeadphonesIcon,
	Home,
	Leaf,
	Lightbulb,
	Mail,
	Shield,
	Target,
	TrendingUp,
	UserCog,
	Users,
	Rocket,
	Award,
	FileText,
	Video,
	MessageSquare,
	Phone,
	MapPin,
	Globe,
	Zap,
	Settings,
	BarChart,
	PieChart,
	Activity,
	Cpu,
	HardDrive,
	Network,
	Lock,
	Key,
	FileCheck,
	Wrench,
	Package,
	Truck,
	DollarSign,
	CreditCard,
	Receipt,
	Building,
	Store,
	Hospital,
	Plane,
	Car,
	ShoppingCart,
	Heart,
	Stethoscope,
	Pill,
	TestTube,
	Microscope,
	Atom,
	Binary,
	Blocks,
	Box,
	Layers,
	Component,
} from 'lucide-react';
import type { MenuItem } from '@/components/menu';
export const navigationMenu: MenuItem[] = [
	{
		id: 'home',
		label: 'Home',
		description: 'Welcome to our comprehensive platform',
		icon: Home,
	},
	{
		id: 'products-services',
		label: 'Products & Services',
		description: 'Explore our comprehensive offerings',
		icon: Grid3x3,
		submenu: [
			{
				id: 'software-solutions',
				label: 'Software Solutions',
				description: 'Custom software development and deployment',
				icon: Code2,
				submenu: [
					{
						id: 'web-development',
						label: 'Web Development',
						description: 'Modern web applications and platforms',
						icon: Globe,
						submenu: [
							{
								id: 'frontend-development',
								label: 'Frontend Development',
								description: 'React, Vue, Angular applications',
								icon: Component,
							},
							{
								id: 'backend-development',
								label: 'Backend Development',
								description: 'Node.js, Python, Java services',
								icon: Database,
							},
							{
								id: 'fullstack-development',
								label: 'Full-Stack Development',
								description: 'End-to-end web solutions',
								icon: Layers,
							},
						],
					},
					{
						id: 'mobile-development',
						label: 'Mobile Development',
						description: 'iOS and Android applications',
						icon: Phone,
						submenu: [
							{
								id: 'native-apps',
								label: 'Native Apps',
								description: 'Swift and Kotlin development',
								icon: Phone,
							},
							{
								id: 'cross-platform',
								label: 'Cross-Platform',
								description: 'React Native and Flutter',
								icon: Grid3x3,
							},
							{
								id: 'pwa',
								label: 'Progressive Web Apps',
								description: 'Modern PWA solutions',
								icon: Globe,
							},
						],
					},
					{
						id: 'enterprise-software',
						label: 'Enterprise Software',
						description: 'Large-scale business applications',
						icon: Building2,
						submenu: [
							{
								id: 'erp-systems',
								label: 'ERP Systems',
								description: 'Enterprise resource planning',
								icon: Package,
							},
							{
								id: 'crm-solutions',
								label: 'CRM Solutions',
								description: 'Customer relationship management',
								icon: Users,
							},
							{
								id: 'workflow-automation',
								label: 'Workflow Automation',
								description: 'Business process automation',
								icon: Zap,
							},
						],
					},
				],
			},
			{
				id: 'cloud-infrastructure',
				label: 'Cloud & Infrastructure',
				description: 'Scalable cloud solutions and infrastructure',
				icon: Cloud,
				submenu: [
					{
						id: 'cloud-migration',
						label: 'Cloud Migration',
						description: 'Seamless migration to cloud platforms',
						icon: Rocket,
						submenu: [
							{
								id: 'aws-migration',
								label: 'AWS Migration',
								description: 'Amazon Web Services migration',
								icon: Cloud,
							},
							{
								id: 'azure-migration',
								label: 'Azure Migration',
								description: 'Microsoft Azure migration',
								icon: Cloud,
							},
							{
								id: 'gcp-migration',
								label: 'GCP Migration',
								description: 'Google Cloud Platform migration',
								icon: Cloud,
							},
						],
					},
					{
						id: 'infrastructure-management',
						label: 'Infrastructure Management',
						description: 'Comprehensive infrastructure services',
						icon: Network,
						submenu: [
							{
								id: 'server-management',
								label: 'Server Management',
								description: 'Server provisioning and maintenance',
								icon: HardDrive,
							},
							{
								id: 'network-management',
								label: 'Network Management',
								description: 'Network design and optimization',
								icon: Network,
							},
							{
								id: 'storage-solutions',
								label: 'Storage Solutions',
								description: 'Data storage and backup',
								icon: Database,
							},
						],
					},
					{
						id: 'containerization',
						label: 'Containerization',
						description: 'Docker and Kubernetes solutions',
						icon: Box,
						submenu: [
							{
								id: 'docker-services',
								label: 'Docker Services',
								description: 'Container development and deployment',
								icon: Box,
							},
							{
								id: 'kubernetes-orchestration',
								label: 'Kubernetes Orchestration',
								description: 'Container orchestration at scale',
								icon: Blocks,
							},
							{
								id: 'microservices',
								label: 'Microservices Architecture',
								description: 'Microservices design and implementation',
								icon: Component,
							},
						],
					},
				],
			},
			{
				id: 'consulting-services',
				label: 'Consulting Services',
				description: 'Expert guidance and strategic support',
				icon: Users,
				submenu: [
					{
						id: 'technical-consulting',
						label: 'Technical Consulting',
						description: 'Architecture and implementation guidance',
						icon: Code2,
						submenu: [
							{
								id: 'system-architecture',
								label: 'System Architecture',
								description: 'Scalable system design and planning',
								icon: Grid3x3,
							},
							{
								id: 'performance-optimization',
								label: 'Performance Optimization',
								description: 'Application and system optimization',
								icon: Zap,
							},
							{
								id: 'security-audits',
								label: 'Security Audits',
								description: 'Comprehensive security assessments',
								icon: Shield,
							},
						],
					},
					{
						id: 'business-strategy',
						label: 'Business Strategy',
						description: 'Digital transformation and business planning',
						icon: Briefcase,
						submenu: [
							{
								id: 'digital-strategy',
								label: 'Digital Strategy',
								description: 'Digital transformation roadmaps',
								icon: Lightbulb,
							},
							{
								id: 'market-analysis',
								label: 'Market Analysis',
								description: 'Competitive analysis and positioning',
								icon: BarChart,
							},
							{
								id: 'roi-optimization',
								label: 'ROI Optimization',
								description: 'Return on investment strategies',
								icon: TrendingUp,
							},
						],
					},
					{
						id: 'training-workshops',
						label: 'Training & Workshops',
						description: 'Team skill development and knowledge transfer',
						icon: GraduationCap,
						submenu: [
							{
								id: 'technical-training',
								label: 'Technical Training',
								description: 'Programming and technology skills',
								icon: Code2,
							},
							{
								id: 'agile-methodologies',
								label: 'Agile Methodologies',
								description: 'Scrum, Kanban, and agile practices',
								icon: Target,
							},
							{
								id: 'leadership-management',
								label: 'Leadership & Management',
								description: 'Technical leadership and team management',
								icon: UserCog,
							},
						],
					},
				],
			},
			{
				id: 'digital-transformation',
				label: 'Digital Transformation',
				description: 'Comprehensive digital transformation strategies',
				icon: Lightbulb,
				submenu: [
					{
						id: 'process-automation',
						label: 'Process Automation',
						description: 'Automate business processes',
						icon: Zap,
						submenu: [
							{
								id: 'rpa-solutions',
								label: 'RPA Solutions',
								description: 'Robotic process automation',
								icon: Cpu,
							},
							{
								id: 'workflow-optimization',
								label: 'Workflow Optimization',
								description: 'Streamline business workflows',
								icon: Activity,
							},
							{
								id: 'integration-services',
								label: 'Integration Services',
								description: 'System and application integration',
								icon: Network,
							},
						],
					},
					{
						id: 'legacy-modernization',
						label: 'Legacy Modernization',
						description: 'Modernize legacy systems',
						icon: Settings,
						submenu: [
							{
								id: 'application-refactoring',
								label: 'Application Refactoring',
								description: 'Modernize existing applications',
								icon: Code2,
							},
							{
								id: 'database-migration',
								label: 'Database Migration',
								description: 'Migrate to modern databases',
								icon: Database,
							},
							{
								id: 'api-development',
								label: 'API Development',
								description: 'Build modern APIs',
								icon: Binary,
							},
						],
					},
				],
			},
			{
				id: 'cybersecurity-consulting',
				label: 'Cybersecurity Consulting',
				description: 'Comprehensive cybersecurity services and solutions',
				icon: Shield,
				submenu: [
					{
						id: 'security-assessment',
						label: 'Security Assessment',
						description: 'Comprehensive security evaluations',
						icon: FileCheck,
						submenu: [
							{
								id: 'penetration-testing',
								label: 'Penetration Testing',
								description: 'Ethical hacking and vulnerability testing',
								icon: Target,
							},
							{
								id: 'vulnerability-scanning',
								label: 'Vulnerability Scanning',
								description: 'Automated security scanning',
								icon: Activity,
							},
							{
								id: 'compliance-audits',
								label: 'Compliance Audits',
								description: 'Regulatory compliance assessments',
								icon: FileText,
							},
						],
					},
					{
						id: 'security-implementation',
						label: 'Security Implementation',
						description: 'Deploy security solutions',
						icon: Lock,
						submenu: [
							{
								id: 'firewall-setup',
								label: 'Firewall Setup',
								description: 'Network firewall configuration',
								icon: Shield,
							},
							{
								id: 'encryption-services',
								label: 'Encryption Services',
								description: 'Data encryption solutions',
								icon: Key,
							},
							{
								id: 'access-control',
								label: 'Access Control',
								description: 'Identity and access management',
								icon: Lock,
							},
						],
					},
				],
			},
			{
				id: 'data-analytics',
				label: 'Data & Analytics Consulting',
				description: 'Data strategy, analytics, and business intelligence',
				icon: Database,
				submenu: [
					{
						id: 'business-intelligence',
						label: 'Business Intelligence',
						description: 'BI solutions and dashboards',
						icon: BarChart,
						submenu: [
							{
								id: 'dashboard-development',
								label: 'Dashboard Development',
								description: 'Interactive data dashboards',
								icon: PieChart,
							},
							{
								id: 'reporting-solutions',
								label: 'Reporting Solutions',
								description: 'Automated reporting systems',
								icon: FileText,
							},
							{
								id: 'data-visualization',
								label: 'Data Visualization',
								description: 'Visual data representation',
								icon: BarChart,
							},
						],
					},
					{
						id: 'data-engineering',
						label: 'Data Engineering',
						description: 'Data pipeline and infrastructure',
						icon: Database,
						submenu: [
							{
								id: 'data-warehousing',
								label: 'Data Warehousing',
								description: 'Enterprise data warehouse solutions',
								icon: HardDrive,
							},
							{
								id: 'etl-pipelines',
								label: 'ETL Pipelines',
								description: 'Extract, transform, load processes',
								icon: Activity,
							},
							{
								id: 'data-lakes',
								label: 'Data Lakes',
								description: 'Scalable data lake architecture',
								icon: Database,
							},
						],
					},
					{
						id: 'machine-learning',
						label: 'Machine Learning',
						description: 'AI and ML solutions',
						icon: Cpu,
						submenu: [
							{
								id: 'predictive-analytics',
								label: 'Predictive Analytics',
								description: 'Forecasting and prediction models',
								icon: TrendingUp,
							},
							{
								id: 'nlp-solutions',
								label: 'NLP Solutions',
								description: 'Natural language processing',
								icon: MessageSquare,
							},
							{
								id: 'computer-vision',
								label: 'Computer Vision',
								description: 'Image and video analysis',
								icon: Activity,
							},
						],
					},
				],
			},
			{
				id: 'devops-platform',
				label: 'DevOps & Platform Engineering',
				description: 'DevOps transformation and platform engineering',
				icon: GitBranch,
				submenu: [
					{
						id: 'ci-cd-pipelines',
						label: 'CI/CD Pipelines',
						description: 'Continuous integration and deployment',
						icon: GitBranch,
						submenu: [
							{
								id: 'jenkins-setup',
								label: 'Jenkins Setup',
								description: 'Jenkins pipeline configuration',
								icon: Settings,
							},
							{
								id: 'github-actions',
								label: 'GitHub Actions',
								description: 'GitHub workflow automation',
								icon: GitBranch,
							},
							{
								id: 'gitlab-ci',
								label: 'GitLab CI',
								description: 'GitLab CI/CD implementation',
								icon: GitBranch,
							},
						],
					},
					{
						id: 'infrastructure-as-code',
						label: 'Infrastructure as Code',
						description: 'IaC implementation and management',
						icon: Code2,
						submenu: [
							{
								id: 'terraform',
								label: 'Terraform',
								description: 'Terraform infrastructure provisioning',
								icon: Cloud,
							},
							{
								id: 'ansible',
								label: 'Ansible',
								description: 'Configuration management with Ansible',
								icon: Settings,
							},
							{
								id: 'cloudformation',
								label: 'CloudFormation',
								description: 'AWS CloudFormation templates',
								icon: Cloud,
							},
						],
					},
					{
						id: 'monitoring-observability',
						label: 'Monitoring & Observability',
						description: 'System monitoring and logging',
						icon: Activity,
						submenu: [
							{
								id: 'prometheus-grafana',
								label: 'Prometheus & Grafana',
								description: 'Metrics and visualization',
								icon: BarChart,
							},
							{
								id: 'elk-stack',
								label: 'ELK Stack',
								description: 'Elasticsearch, Logstash, Kibana',
								icon: Database,
							},
							{
								id: 'apm-solutions',
								label: 'APM Solutions',
								description: 'Application performance monitoring',
								icon: Activity,
							},
						],
					},
				],
			},
			{
				id: 'support-maintenance',
				label: 'Support & Maintenance',
				description: 'Ongoing maintenance and support services',
				icon: HeadphonesIcon,
				submenu: [
					{
						id: 'technical-support',
						label: 'Technical Support',
						description: '24/7 technical assistance',
						icon: HeadphonesIcon,
						submenu: [
							{
								id: 'tier-1-support',
								label: 'Tier 1 Support',
								description: 'Basic troubleshooting and assistance',
								icon: HeadphonesIcon,
							},
							{
								id: 'tier-2-support',
								label: 'Tier 2 Support',
								description: 'Advanced technical support',
								icon: Wrench,
							},
							{
								id: 'tier-3-support',
								label: 'Tier 3 Support',
								description: 'Expert-level support',
								icon: UserCog,
							},
						],
					},
					{
						id: 'maintenance-services',
						label: 'Maintenance Services',
						description: 'Proactive system maintenance',
						icon: Wrench,
						submenu: [
							{
								id: 'preventive-maintenance',
								label: 'Preventive Maintenance',
								description: 'Regular system health checks',
								icon: FileCheck,
							},
							{
								id: 'corrective-maintenance',
								label: 'Corrective Maintenance',
								description: 'Issue resolution and fixes',
								icon: Wrench,
							},
							{
								id: 'adaptive-maintenance',
								label: 'Adaptive Maintenance',
								description: 'System updates and improvements',
								icon: Settings,
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'industry-solutions',
		label: 'Industry Solutions',
		description: 'Specialized solutions for different industries',
		icon: Factory,
		submenu: [
			{
				id: 'healthcare',
				label: 'Healthcare',
				description: 'Healthcare technology solutions',
				icon: Heart,
				submenu: [
					{
						id: 'hospital-management',
						label: 'Hospital Management',
						description: 'Complete hospital management systems',
						icon: Hospital,
						submenu: [
							{
								id: 'patient-records',
								label: 'Patient Records',
								description: 'Electronic health records',
								icon: FileText,
							},
							{
								id: 'appointment-scheduling',
								label: 'Appointment Scheduling',
								description: 'Patient appointment management',
								icon: Target,
							},
							{
								id: 'billing-insurance',
								label: 'Billing & Insurance',
								description: 'Medical billing systems',
								icon: Receipt,
							},
						],
					},
					{
						id: 'telemedicine',
						label: 'Telemedicine',
						description: 'Remote healthcare solutions',
						icon: Video,
						submenu: [
							{
								id: 'virtual-consultations',
								label: 'Virtual Consultations',
								description: 'Video consultation platform',
								icon: Video,
							},
							{
								id: 'remote-monitoring',
								label: 'Remote Monitoring',
								description: 'Patient health monitoring',
								icon: Activity,
							},
							{
								id: 'prescription-management',
								label: 'Prescription Management',
								description: 'Digital prescription system',
								icon: Pill,
							},
						],
					},
					{
						id: 'medical-research',
						label: 'Medical Research',
						description: 'Research and clinical trials',
						icon: FlaskConical,
						submenu: [
							{
								id: 'clinical-trials',
								label: 'Clinical Trials',
								description: 'Trial management systems',
								icon: TestTube,
							},
							{
								id: 'lab-information',
								label: 'Lab Information Systems',
								description: 'Laboratory data management',
								icon: Microscope,
							},
							{
								id: 'research-analytics',
								label: 'Research Analytics',
								description: 'Medical data analysis',
								icon: BarChart,
							},
						],
					},
				],
			},
			{
				id: 'finance-banking',
				label: 'Finance & Banking',
				description: 'Financial technology solutions',
				icon: DollarSign,
				submenu: [
					{
						id: 'digital-banking',
						label: 'Digital Banking',
						description: 'Online and mobile banking',
						icon: CreditCard,
						submenu: [
							{
								id: 'mobile-banking',
								label: 'Mobile Banking',
								description: 'Mobile banking applications',
								icon: Phone,
							},
							{
								id: 'online-banking',
								label: 'Online Banking',
								description: 'Web-based banking platform',
								icon: Globe,
							},
							{
								id: 'payment-processing',
								label: 'Payment Processing',
								description: 'Secure payment systems',
								icon: CreditCard,
							},
						],
					},
					{
						id: 'wealth-management',
						label: 'Wealth Management',
						description: 'Investment and portfolio management',
						icon: TrendingUp,
						submenu: [
							{
								id: 'portfolio-management',
								label: 'Portfolio Management',
								description: 'Investment portfolio tracking',
								icon: PieChart,
							},
							{
								id: 'robo-advisory',
								label: 'Robo-Advisory',
								description: 'Automated investment advice',
								icon: Cpu,
							},
							{
								id: 'risk-assessment',
								label: 'Risk Assessment',
								description: 'Investment risk analysis',
								icon: Shield,
							},
						],
					},
					{
						id: 'compliance-reporting',
						label: 'Compliance & Reporting',
						description: 'Regulatory compliance solutions',
						icon: FileCheck,
						submenu: [
							{
								id: 'kyc-aml',
								label: 'KYC & AML',
								description: 'Know Your Customer and Anti-Money Laundering',
								icon: Shield,
							},
							{
								id: 'regulatory-reporting',
								label: 'Regulatory Reporting',
								description: 'Automated compliance reporting',
								icon: FileText,
							},
							{
								id: 'audit-trails',
								label: 'Audit Trails',
								description: 'Transaction audit systems',
								icon: Activity,
							},
						],
					},
				],
			},
			{
				id: 'retail-ecommerce',
				label: 'Retail & E-commerce',
				description: 'Retail and online commerce solutions',
				icon: ShoppingCart,
				submenu: [
					{
						id: 'ecommerce-platforms',
						label: 'E-commerce Platforms',
						description: 'Online store solutions',
						icon: Store,
						submenu: [
							{
								id: 'storefront-development',
								label: 'Storefront Development',
								description: 'Custom online stores',
								icon: Store,
							},
							{
								id: 'marketplace-solutions',
								label: 'Marketplace Solutions',
								description: 'Multi-vendor marketplaces',
								icon: Grid3x3,
							},
							{
								id: 'mobile-commerce',
								label: 'Mobile Commerce',
								description: 'Mobile shopping apps',
								icon: Phone,
							},
						],
					},
					{
						id: 'inventory-management',
						label: 'Inventory Management',
						description: 'Stock and warehouse management',
						icon: Package,
						submenu: [
							{
								id: 'warehouse-management',
								label: 'Warehouse Management',
								description: 'Warehouse operations system',
								icon: Building,
							},
							{
								id: 'stock-tracking',
								label: 'Stock Tracking',
								description: 'Real-time inventory tracking',
								icon: Activity,
							},
							{
								id: 'order-fulfillment',
								label: 'Order Fulfillment',
								description: 'Order processing and shipping',
								icon: Truck,
							},
						],
					},
					{
						id: 'customer-experience',
						label: 'Customer Experience',
						description: 'Enhance customer engagement',
						icon: Users,
						submenu: [
							{
								id: 'personalization',
								label: 'Personalization',
								description: 'Personalized shopping experience',
								icon: Target,
							},
							{
								id: 'loyalty-programs',
								label: 'Loyalty Programs',
								description: 'Customer rewards systems',
								icon: Award,
							},
							{
								id: 'customer-analytics',
								label: 'Customer Analytics',
								description: 'Shopping behavior analysis',
								icon: BarChart,
							},
						],
					},
				],
			},
			{
				id: 'manufacturing',
				label: 'Manufacturing',
				description: 'Industrial and manufacturing solutions',
				icon: Factory,
				submenu: [
					{
						id: 'production-management',
						label: 'Production Management',
						description: 'Manufacturing execution systems',
						icon: Settings,
						submenu: [
							{
								id: 'production-planning',
								label: 'Production Planning',
								description: 'Manufacturing planning and scheduling',
								icon: Target,
							},
							{
								id: 'quality-control',
								label: 'Quality Control',
								description: 'Quality assurance systems',
								icon: FileCheck,
							},
							{
								id: 'equipment-maintenance',
								label: 'Equipment Maintenance',
								description: 'Predictive maintenance solutions',
								icon: Wrench,
							},
						],
					},
					{
						id: 'supply-chain',
						label: 'Supply Chain',
						description: 'Supply chain optimization',
						icon: Truck,
						submenu: [
							{
								id: 'procurement',
								label: 'Procurement',
								description: 'Supplier and procurement management',
								icon: Package,
							},
							{
								id: 'logistics',
								label: 'Logistics',
								description: 'Transportation and logistics',
								icon: Truck,
							},
							{
								id: 'demand-forecasting',
								label: 'Demand Forecasting',
								description: 'Predictive demand planning',
								icon: TrendingUp,
							},
						],
					},
					{
						id: 'iot-automation',
						label: 'IoT & Automation',
						description: 'Industrial IoT solutions',
						icon: Cpu,
						submenu: [
							{
								id: 'sensor-networks',
								label: 'Sensor Networks',
								description: 'Industrial sensor systems',
								icon: Network,
							},
							{
								id: 'robotics',
								label: 'Robotics',
								description: 'Industrial robotics integration',
								icon: Cpu,
							},
							{
								id: 'real-time-monitoring',
								label: 'Real-time Monitoring',
								description: 'Production monitoring systems',
								icon: Activity,
							},
						],
					},
				],
			},
			{
				id: 'transportation',
				label: 'Transportation & Logistics',
				description: 'Transportation industry solutions',
				icon: Truck,
				submenu: [
					{
						id: 'fleet-management',
						label: 'Fleet Management',
						description: 'Vehicle fleet tracking and management',
						icon: Car,
						submenu: [
							{
								id: 'gps-tracking',
								label: 'GPS Tracking',
								description: 'Real-time vehicle tracking',
								icon: MapPin,
							},
							{
								id: 'route-optimization',
								label: 'Route Optimization',
								description: 'Intelligent route planning',
								icon: Target,
							},
							{
								id: 'fuel-management',
								label: 'Fuel Management',
								description: 'Fuel consumption tracking',
								icon: Activity,
							},
						],
					},
					{
						id: 'booking-systems',
						label: 'Booking Systems',
						description: 'Reservation and booking platforms',
						icon: Plane,
						submenu: [
							{
								id: 'airline-booking',
								label: 'Airline Booking',
								description: 'Flight reservation systems',
								icon: Plane,
							},
							{
								id: 'hotel-booking',
								label: 'Hotel Booking',
								description: 'Hotel reservation platform',
								icon: Building,
							},
							{
								id: 'car-rental',
								label: 'Car Rental',
								description: 'Vehicle rental systems',
								icon: Car,
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'company',
		label: 'Company',
		description: 'Learn about our organization and culture',
		icon: Building2,
		submenu: [
			{
				id: 'about-us',
				label: 'About Us',
				description: 'Our story, mission, and values',
				icon: Building2,
				submenu: [
					{
						id: 'our-story',
						label: 'Our Story',
						description: 'Company history and journey',
						icon: BookOpen,
					},
					{
						id: 'mission-vision',
						label: 'Mission & Vision',
						description: 'Our purpose and future goals',
						icon: Target,
					},
					{
						id: 'core-values',
						label: 'Core Values',
						description: 'Principles that guide us',
						icon: Heart,
					},
				],
			},
			{
				id: 'leadership',
				label: 'Leadership',
				description: 'Meet our executive team',
				icon: UserCog,
				submenu: [
					{
						id: 'executive-team',
						label: 'Executive Team',
						description: 'C-level executives',
						icon: Users,
					},
					{
						id: 'board-directors',
						label: 'Board of Directors',
						description: 'Company board members',
						icon: Briefcase,
					},
					{
						id: 'advisory-board',
						label: 'Advisory Board',
						description: 'Strategic advisors',
						icon: GraduationCap,
					},
				],
			},
			{
				id: 'careers',
				label: 'Careers',
				description: 'Join our team',
				icon: Briefcase,
				submenu: [
					{
						id: 'open-positions',
						label: 'Open Positions',
						description: 'Current job openings',
						icon: FileText,
					},
					{
						id: 'culture-benefits',
						label: 'Culture & Benefits',
						description: 'Work environment and perks',
						icon: Heart,
					},
					{
						id: 'internships',
						label: 'Internships',
						description: 'Internship opportunities',
						icon: GraduationCap,
					},
				],
			},
			{
				id: 'news-media',
				label: 'News & Media',
				description: 'Latest company news',
				icon: FileText,
				submenu: [
					{
						id: 'press-releases',
						label: 'Press Releases',
						description: 'Official announcements',
						icon: FileText,
					},
					{
						id: 'media-kit',
						label: 'Media Kit',
						description: 'Brand assets and resources',
						icon: Package,
					},
					{
						id: 'blog',
						label: 'Blog',
						description: 'Company blog and insights',
						icon: BookOpen,
					},
				],
			},
			{
				id: 'partnerships',
				label: 'Partnerships',
				description: 'Partner with us',
				icon: Users,
				submenu: [
					{
						id: 'technology-partners',
						label: 'Technology Partners',
						description: 'Strategic technology alliances',
						icon: Code2,
					},
					{
						id: 'channel-partners',
						label: 'Channel Partners',
						description: 'Reseller and distribution partners',
						icon: Network,
					},
					{
						id: 'become-partner',
						label: 'Become a Partner',
						description: 'Partnership opportunities',
						icon: Briefcase,
					},
				],
			},
		],
	},
	{
		id: 'resources',
		label: 'Resources',
		description: 'Knowledge base, tools, and learning materials',
		icon: BookOpen,
		submenu: [
			{
				id: 'documentation',
				label: 'Documentation',
				description: 'Technical documentation and guides',
				icon: FileText,
				submenu: [
					{
						id: 'api-docs',
						label: 'API Documentation',
						description: 'API reference and guides',
						icon: Code2,
						submenu: [
							{
								id: 'rest-api',
								label: 'REST API',
								description: 'RESTful API documentation',
								icon: Binary,
							},
							{
								id: 'graphql-api',
								label: 'GraphQL API',
								description: 'GraphQL API reference',
								icon: Network,
							},
							{
								id: 'webhooks',
								label: 'Webhooks',
								description: 'Webhook integration guide',
								icon: Zap,
							},
						],
					},
					{
						id: 'user-guides',
						label: 'User Guides',
						description: 'Product user documentation',
						icon: BookOpen,
						submenu: [
							{
								id: 'getting-started',
								label: 'Getting Started',
								description: 'Quick start guides',
								icon: Rocket,
							},
							{
								id: 'tutorials',
								label: 'Tutorials',
								description: 'Step-by-step tutorials',
								icon: GraduationCap,
							},
							{
								id: 'best-practices',
								label: 'Best Practices',
								description: 'Recommended practices',
								icon: Award,
							},
						],
					},
					{
						id: 'technical-specs',
						label: 'Technical Specifications',
						description: 'Detailed technical specs',
						icon: FileCheck,
						submenu: [
							{
								id: 'system-requirements',
								label: 'System Requirements',
								description: 'Hardware and software requirements',
								icon: Cpu,
							},
							{
								id: 'architecture-docs',
								label: 'Architecture Documentation',
								description: 'System architecture details',
								icon: Grid3x3,
							},
							{
								id: 'security-specs',
								label: 'Security Specifications',
								description: 'Security standards and protocols',
								icon: Shield,
							},
						],
					},
				],
			},
			{
				id: 'learning-center',
				label: 'Learning Center',
				description: 'Educational resources and courses',
				icon: GraduationCap,
				submenu: [
					{
						id: 'online-courses',
						label: 'Online Courses',
						description: 'Self-paced learning courses',
						icon: Video,
						submenu: [
							{
								id: 'beginner-courses',
								label: 'Beginner Courses',
								description: 'Introduction to our platform',
								icon: GraduationCap,
							},
							{
								id: 'advanced-courses',
								label: 'Advanced Courses',
								description: 'Advanced topics and techniques',
								icon: Award,
							},
							{
								id: 'certification',
								label: 'Certification Programs',
								description: 'Professional certifications',
								icon: Award,
							},
						],
					},
					{
						id: 'webinars',
						label: 'Webinars',
						description: 'Live and recorded webinars',
						icon: Video,
						submenu: [
							{
								id: 'upcoming-webinars',
								label: 'Upcoming Webinars',
								description: 'Register for live sessions',
								icon: Target,
							},
							{
								id: 'webinar-recordings',
								label: 'Webinar Recordings',
								description: 'Watch past webinars',
								icon: Video,
							},
							{
								id: 'workshop-series',
								label: 'Workshop Series',
								description: 'Hands-on workshop sessions',
								icon: Wrench,
							},
						],
					},
					{
						id: 'case-studies',
						label: 'Case Studies',
						description: 'Customer success stories',
						icon: FileText,
						submenu: [
							{
								id: 'enterprise-cases',
								label: 'Enterprise Case Studies',
								description: 'Large enterprise implementations',
								icon: Building2,
							},
							{
								id: 'startup-cases',
								label: 'Startup Case Studies',
								description: 'Startup success stories',
								icon: Rocket,
							},
							{
								id: 'industry-cases',
								label: 'Industry Case Studies',
								description: 'Industry-specific examples',
								icon: Factory,
							},
						],
					},
				],
			},
			{
				id: 'developer-tools',
				label: 'Developer Tools',
				description: 'Tools and SDKs for developers',
				icon: Code2,
				submenu: [
					{
						id: 'sdks',
						label: 'SDKs',
						description: 'Software development kits',
						icon: Package,
						submenu: [
							{
								id: 'javascript-sdk',
								label: 'JavaScript SDK',
								description: 'JavaScript/TypeScript SDK',
								icon: Code2,
							},
							{
								id: 'python-sdk',
								label: 'Python SDK',
								description: 'Python SDK',
								icon: Code2,
							},
							{
								id: 'mobile-sdks',
								label: 'Mobile SDKs',
								description: 'iOS and Android SDKs',
								icon: Phone,
							},
						],
					},
					{
						id: 'cli-tools',
						label: 'CLI Tools',
						description: 'Command-line interface tools',
						icon: Binary,
						submenu: [
							{
								id: 'installation',
								label: 'Installation',
								description: 'Install CLI tools',
								icon: Package,
							},
							{
								id: 'commands',
								label: 'Commands',
								description: 'CLI command reference',
								icon: FileText,
							},
							{
								id: 'automation',
								label: 'Automation',
								description: 'Automate with CLI',
								icon: Zap,
							},
						],
					},
					{
						id: 'code-samples',
						label: 'Code Samples',
						description: 'Example code and snippets',
						icon: Code2,
						submenu: [
							{
								id: 'quick-start',
								label: 'Quick Start Examples',
								description: 'Get started quickly',
								icon: Rocket,
							},
							{
								id: 'integration-examples',
								label: 'Integration Examples',
								description: 'Common integration patterns',
								icon: Network,
							},
							{
								id: 'sample-projects',
								label: 'Sample Projects',
								description: 'Complete example projects',
								icon: Package,
							},
						],
					},
				],
			},
			{
				id: 'community',
				label: 'Community',
				description: 'Connect with other users',
				icon: Users,
				submenu: [
					{
						id: 'forums',
						label: 'Forums',
						description: 'Community discussion forums',
						icon: MessageSquare,
						submenu: [
							{
								id: 'general-discussion',
								label: 'General Discussion',
								description: 'General topics and questions',
								icon: MessageSquare,
							},
							{
								id: 'technical-help',
								label: 'Technical Help',
								description: 'Get technical assistance',
								icon: HeadphonesIcon,
							},
							{
								id: 'feature-requests',
								label: 'Feature Requests',
								description: 'Suggest new features',
								icon: Lightbulb,
							},
						],
					},
					{
						id: 'events',
						label: 'Events',
						description: 'Community events and meetups',
						icon: Users,
						submenu: [
							{
								id: 'conferences',
								label: 'Conferences',
								description: 'Annual conferences',
								icon: Building2,
							},
							{
								id: 'meetups',
								label: 'Meetups',
								description: 'Local community meetups',
								icon: MapPin,
							},
							{
								id: 'hackathons',
								label: 'Hackathons',
								description: 'Coding competitions',
								icon: Code2,
							},
						],
					},
					{
						id: 'user-groups',
						label: 'User Groups',
						description: 'Join user groups',
						icon: Users,
						submenu: [
							{
								id: 'regional-groups',
								label: 'Regional Groups',
								description: 'Location-based groups',
								icon: MapPin,
							},
							{
								id: 'special-interest',
								label: 'Special Interest Groups',
								description: 'Topic-focused groups',
								icon: Target,
							},
							{
								id: 'beta-testers',
								label: 'Beta Testers',
								description: 'Early access program',
								icon: FlaskConical,
							},
						],
					},
				],
			},
			{
				id: 'downloads',
				label: 'Downloads',
				description: 'Software and resources',
				icon: Package,
				submenu: [
					{
						id: 'software',
						label: 'Software',
						description: 'Download our software',
						icon: Package,
						submenu: [
							{
								id: 'desktop-apps',
								label: 'Desktop Applications',
								description: 'Windows, Mac, Linux apps',
								icon: Cpu,
							},
							{
								id: 'mobile-apps',
								label: 'Mobile Applications',
								description: 'iOS and Android apps',
								icon: Phone,
							},
							{
								id: 'browser-extensions',
								label: 'Browser Extensions',
								description: 'Chrome, Firefox extensions',
								icon: Globe,
							},
						],
					},
					{
						id: 'templates',
						label: 'Templates',
						description: 'Project templates and starters',
						icon: FileText,
						submenu: [
							{
								id: 'project-templates',
								label: 'Project Templates',
								description: 'Starter project templates',
								icon: Rocket,
							},
							{
								id: 'design-templates',
								label: 'Design Templates',
								description: 'UI/UX design templates',
								icon: Grid3x3,
							},
							{
								id: 'document-templates',
								label: 'Document Templates',
								description: 'Documentation templates',
								icon: FileText,
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'support',
		label: 'Support',
		description: 'Get help and support when you need it',
		icon: HeadphonesIcon,
		submenu: [
			{
				id: 'help-center',
				label: 'Help Center',
				description: 'Find answers to common questions',
				icon: HeadphonesIcon,
				submenu: [
					{
						id: 'faq',
						label: 'FAQ',
						description: 'Frequently asked questions',
						icon: MessageSquare,
						submenu: [
							{
								id: 'general-faq',
								label: 'General FAQ',
								description: 'General questions',
								icon: MessageSquare,
							},
							{
								id: 'technical-faq',
								label: 'Technical FAQ',
								description: 'Technical questions',
								icon: Code2,
							},
							{
								id: 'billing-faq',
								label: 'Billing FAQ',
								description: 'Billing and payment questions',
								icon: Receipt,
							},
						],
					},
					{
						id: 'knowledge-base',
						label: 'Knowledge Base',
						description: 'Searchable help articles',
						icon: BookOpen,
						submenu: [
							{
								id: 'getting-started-kb',
								label: 'Getting Started',
								description: 'Initial setup guides',
								icon: Rocket,
							},
							{
								id: 'troubleshooting',
								label: 'Troubleshooting',
								description: 'Common issues and solutions',
								icon: Wrench,
							},
							{
								id: 'how-to-guides',
								label: 'How-To Guides',
								description: 'Step-by-step instructions',
								icon: FileText,
							},
						],
					},
					{
						id: 'video-tutorials',
						label: 'Video Tutorials',
						description: 'Visual learning resources',
						icon: Video,
						submenu: [
							{
								id: 'basic-tutorials',
								label: 'Basic Tutorials',
								description: 'Beginner-friendly videos',
								icon: Video,
							},
							{
								id: 'advanced-tutorials',
								label: 'Advanced Tutorials',
								description: 'Advanced feature videos',
								icon: Award,
							},
							{
								id: 'tips-tricks',
								label: 'Tips & Tricks',
								description: 'Productivity tips',
								icon: Lightbulb,
							},
						],
					},
				],
			},
			{
				id: 'contact-support',
				label: 'Contact Support',
				description: 'Reach out to our support team',
				icon: Mail,
				submenu: [
					{
						id: 'submit-ticket',
						label: 'Submit a Ticket',
						description: 'Create a support ticket',
						icon: FileText,
						submenu: [
							{
								id: 'technical-issue',
								label: 'Technical Issue',
								description: 'Report technical problems',
								icon: Wrench,
							},
							{
								id: 'billing-inquiry',
								label: 'Billing Inquiry',
								description: 'Billing questions',
								icon: Receipt,
							},
							{
								id: 'feature-request-support',
								label: 'Feature Request',
								description: 'Request new features',
								icon: Lightbulb,
							},
						],
					},
					{
						id: 'live-chat',
						label: 'Live Chat',
						description: 'Chat with support agents',
						icon: MessageSquare,
						submenu: [
							{
								id: 'sales-chat',
								label: 'Sales Chat',
								description: 'Talk to sales team',
								icon: Briefcase,
							},
							{
								id: 'technical-chat',
								label: 'Technical Chat',
								description: 'Technical support chat',
								icon: Code2,
							},
							{
								id: 'general-chat',
								label: 'General Chat',
								description: 'General inquiries',
								icon: MessageSquare,
							},
						],
					},
					{
						id: 'phone-support',
						label: 'Phone Support',
						description: 'Call our support team',
						icon: Phone,
						submenu: [
							{
								id: 'support-hours',
								label: 'Support Hours',
								description: "When we're available",
								icon: Target,
							},
							{
								id: 'regional-numbers',
								label: 'Regional Numbers',
								description: 'Phone numbers by region',
								icon: MapPin,
							},
							{
								id: 'emergency-support',
								label: 'Emergency Support',
								description: '24/7 critical support',
								icon: Shield,
							},
						],
					},
				],
			},
			{
				id: 'service-status',
				label: 'Service Status',
				description: 'Check system status',
				icon: Activity,
				submenu: [
					{
						id: 'current-status',
						label: 'Current Status',
						description: 'Real-time system status',
						icon: Activity,
						submenu: [
							{
								id: 'all-systems',
								label: 'All Systems',
								description: 'Overall system health',
								icon: Activity,
							},
							{
								id: 'api-status',
								label: 'API Status',
								description: 'API availability',
								icon: Binary,
							},
							{
								id: 'infrastructure-status',
								label: 'Infrastructure Status',
								description: 'Infrastructure health',
								icon: Cloud,
							},
						],
					},
					{
						id: 'incident-history',
						label: 'Incident History',
						description: 'Past incidents and resolutions',
						icon: FileText,
						submenu: [
							{
								id: 'recent-incidents',
								label: 'Recent Incidents',
								description: 'Last 30 days',
								icon: Activity,
							},
							{
								id: 'major-incidents',
								label: 'Major Incidents',
								description: 'Significant outages',
								icon: Shield,
							},
							{
								id: 'maintenance-history',
								label: 'Maintenance History',
								description: 'Scheduled maintenance',
								icon: Wrench,
							},
						],
					},
					{
						id: 'subscribe-updates',
						label: 'Subscribe to Updates',
						description: 'Get status notifications',
						icon: Mail,
						submenu: [
							{
								id: 'email-notifications',
								label: 'Email Notifications',
								description: 'Receive email updates',
								icon: Mail,
							},
							{
								id: 'sms-alerts',
								label: 'SMS Alerts',
								description: 'Text message alerts',
								icon: Phone,
							},
							{
								id: 'webhook-notifications',
								label: 'Webhook Notifications',
								description: 'Automated notifications',
								icon: Zap,
							},
						],
					},
				],
			},
			{
				id: 'feedback',
				label: 'Feedback',
				description: 'Share your thoughts with us',
				icon: MessageSquare,
				submenu: [
					{
						id: 'product-feedback',
						label: 'Product Feedback',
						description: 'Share product suggestions',
						icon: Lightbulb,
						submenu: [
							{
								id: 'feature-suggestions',
								label: 'Feature Suggestions',
								description: 'Suggest new features',
								icon: Lightbulb,
							},
							{
								id: 'bug-reports',
								label: 'Bug Reports',
								description: 'Report bugs',
								icon: Wrench,
							},
							{
								id: 'usability-feedback',
								label: 'Usability Feedback',
								description: 'UX improvement suggestions',
								icon: Users,
							},
						],
					},
					{
						id: 'surveys',
						label: 'Surveys',
						description: 'Participate in surveys',
						icon: FileCheck,
						submenu: [
							{
								id: 'satisfaction-survey',
								label: 'Satisfaction Survey',
								description: 'Rate your experience',
								icon: Heart,
							},
							{
								id: 'feature-priority',
								label: 'Feature Priority',
								description: 'Vote on features',
								icon: Target,
							},
							{
								id: 'user-research',
								label: 'User Research',
								description: 'Join research studies',
								icon: FlaskConical,
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'research-innovation',
		label: 'Research & Innovation',
		description: 'Cutting-edge research and innovation initiatives',
		icon: FlaskConical,
		submenu: [
			{
				id: 'research-labs',
				label: 'Research Labs',
				description: 'Our research facilities and projects',
				icon: Microscope,
				submenu: [
					{
						id: 'ai-research',
						label: 'AI Research',
						description: 'Artificial intelligence research',
						icon: Cpu,
						submenu: [
							{
								id: 'machine-learning-research',
								label: 'Machine Learning',
								description: 'ML algorithms and models',
								icon: Atom,
							},
							{
								id: 'deep-learning',
								label: 'Deep Learning',
								description: 'Neural networks research',
								icon: Network,
							},
							{
								id: 'nlp-research',
								label: 'Natural Language Processing',
								description: 'Language understanding research',
								icon: MessageSquare,
							},
						],
					},
					{
						id: 'quantum-computing',
						label: 'Quantum Computing',
						description: 'Quantum computing research',
						icon: Atom,
						submenu: [
							{
								id: 'quantum-algorithms',
								label: 'Quantum Algorithms',
								description: 'Algorithm development',
								icon: Binary,
							},
							{
								id: 'quantum-applications',
								label: 'Quantum Applications',
								description: 'Practical applications',
								icon: Zap,
							},
							{
								id: 'quantum-hardware',
								label: 'Quantum Hardware',
								description: 'Hardware research',
								icon: Cpu,
							},
						],
					},
					{
						id: 'blockchain-research',
						label: 'Blockchain Research',
						description: 'Distributed ledger technology',
						icon: Blocks,
						submenu: [
							{
								id: 'consensus-mechanisms',
								label: 'Consensus Mechanisms',
								description: 'Blockchain consensus research',
								icon: Network,
							},
							{
								id: 'smart-contracts',
								label: 'Smart Contracts',
								description: 'Smart contract development',
								icon: Code2,
							},
							{
								id: 'scalability',
								label: 'Scalability Solutions',
								description: 'Blockchain scaling research',
								icon: TrendingUp,
							},
						],
					},
				],
			},
			{
				id: 'innovation-programs',
				label: 'Innovation Programs',
				description: 'Programs fostering innovation',
				icon: Lightbulb,
				submenu: [
					{
						id: 'startup-incubator',
						label: 'Startup Incubator',
						description: 'Support for startups',
						icon: Rocket,
						submenu: [
							{
								id: 'application-process',
								label: 'Application Process',
								description: 'How to apply',
								icon: FileText,
							},
							{
								id: 'mentorship',
								label: 'Mentorship',
								description: 'Expert guidance',
								icon: Users,
							},
							{
								id: 'funding-opportunities',
								label: 'Funding Opportunities',
								description: 'Investment and grants',
								icon: DollarSign,
							},
						],
					},
					{
						id: 'innovation-challenges',
						label: 'Innovation Challenges',
						description: 'Competitions and hackathons',
						icon: Award,
						submenu: [
							{
								id: 'current-challenges',
								label: 'Current Challenges',
								description: 'Active competitions',
								icon: Target,
							},
							{
								id: 'past-winners',
								label: 'Past Winners',
								description: 'Previous challenge winners',
								icon: Award,
							},
							{
								id: 'prizes-rewards',
								label: 'Prizes & Rewards',
								description: 'Competition rewards',
								icon: DollarSign,
							},
						],
					},
					{
						id: 'open-innovation',
						label: 'Open Innovation',
						description: 'Collaborative innovation',
						icon: Users,
						submenu: [
							{
								id: 'collaboration-opportunities',
								label: 'Collaboration Opportunities',
								description: 'Partner with us',
								icon: Briefcase,
							},
							{
								id: 'open-source-projects',
								label: 'Open Source Projects',
								description: 'Our open source initiatives',
								icon: GitBranch,
							},
							{
								id: 'academic-partnerships',
								label: 'Academic Partnerships',
								description: 'University collaborations',
								icon: GraduationCap,
							},
						],
					},
				],
			},
			{
				id: 'publications',
				label: 'Publications',
				description: 'Research papers and publications',
				icon: BookOpen,
				submenu: [
					{
						id: 'research-papers',
						label: 'Research Papers',
						description: 'Published research',
						icon: FileText,
						submenu: [
							{
								id: 'peer-reviewed',
								label: 'Peer-Reviewed Papers',
								description: 'Academic publications',
								icon: Award,
							},
							{
								id: 'white-papers',
								label: 'White Papers',
								description: 'Technical white papers',
								icon: FileText,
							},
							{
								id: 'technical-reports',
								label: 'Technical Reports',
								description: 'Research reports',
								icon: BarChart,
							},
						],
					},
					{
						id: 'patents',
						label: 'Patents',
						description: 'Our patent portfolio',
						icon: Shield,
						submenu: [
							{
								id: 'granted-patents',
								label: 'Granted Patents',
								description: 'Approved patents',
								icon: Award,
							},
							{
								id: 'pending-patents',
								label: 'Pending Patents',
								description: 'Patent applications',
								icon: FileText,
							},
							{
								id: 'licensing',
								label: 'Patent Licensing',
								description: 'License our patents',
								icon: Key,
							},
						],
					},
				],
			},
			{
				id: 'future-tech',
				label: 'Future Technologies',
				description: 'Emerging technology exploration',
				icon: Rocket,
				submenu: [
					{
						id: 'emerging-tech',
						label: 'Emerging Technologies',
						description: 'Next-generation tech',
						icon: Zap,
						submenu: [
							{
								id: 'edge-computing',
								label: 'Edge Computing',
								description: 'Distributed computing research',
								icon: Network,
							},
							{
								id: '5g-6g',
								label: '5G & 6G',
								description: 'Next-gen connectivity',
								icon: Activity,
							},
							{
								id: 'ar-vr',
								label: 'AR/VR',
								description: 'Immersive technologies',
								icon: Grid3x3,
							},
						],
					},
					{
						id: 'tech-forecasting',
						label: 'Technology Forecasting',
						description: 'Future technology trends',
						icon: TrendingUp,
						submenu: [
							{
								id: 'trend-analysis',
								label: 'Trend Analysis',
								description: 'Technology trend reports',
								icon: BarChart,
							},
							{
								id: 'future-scenarios',
								label: 'Future Scenarios',
								description: 'Technology scenarios',
								icon: Lightbulb,
							},
							{
								id: 'roadmaps',
								label: 'Technology Roadmaps',
								description: 'Future development plans',
								icon: Target,
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'sustainability',
		label: 'Sustainability',
		description: 'Environmental responsibility and sustainable technology',
		icon: Leaf,
		submenu: [
			{
				id: 'environmental-initiatives',
				label: 'Environmental Initiatives',
				description: 'Our environmental programs',
				icon: Leaf,
				submenu: [
					{
						id: 'carbon-neutrality',
						label: 'Carbon Neutrality',
						description: 'Carbon reduction efforts',
						icon: Cloud,
						submenu: [
							{
								id: 'emissions-reduction',
								label: 'Emissions Reduction',
								description: 'Reducing carbon footprint',
								icon: TrendingUp,
							},
							{
								id: 'renewable-energy',
								label: 'Renewable Energy',
								description: 'Clean energy usage',
								icon: Zap,
							},
							{
								id: 'carbon-offsets',
								label: 'Carbon Offsets',
								description: 'Offset programs',
								icon: Leaf,
							},
						],
					},
					{
						id: 'green-technology',
						label: 'Green Technology',
						description: 'Sustainable tech solutions',
						icon: Cpu,
						submenu: [
							{
								id: 'energy-efficient',
								label: 'Energy Efficient Systems',
								description: 'Low-power computing',
								icon: Zap,
							},
							{
								id: 'green-data-centers',
								label: 'Green Data Centers',
								description: 'Sustainable infrastructure',
								icon: HardDrive,
							},
							{
								id: 'circular-economy',
								label: 'Circular Economy',
								description: 'Resource recycling',
								icon: Activity,
							},
						],
					},
					{
						id: 'waste-reduction',
						label: 'Waste Reduction',
						description: 'Minimizing waste',
						icon: Leaf,
						submenu: [
							{
								id: 'recycling-programs',
								label: 'Recycling Programs',
								description: 'E-waste recycling',
								icon: Activity,
							},
							{
								id: 'sustainable-packaging',
								label: 'Sustainable Packaging',
								description: 'Eco-friendly packaging',
								icon: Package,
							},
							{
								id: 'zero-waste',
								label: 'Zero Waste Goals',
								description: 'Waste elimination targets',
								icon: Target,
							},
						],
					},
				],
			},
			{
				id: 'sustainability-reports',
				label: 'Sustainability Reports',
				description: 'Environmental impact reports',
				icon: FileText,
				submenu: [
					{
						id: 'annual-reports',
						label: 'Annual Reports',
						description: 'Yearly sustainability reports',
						icon: FileText,
						submenu: [
							{
								id: 'current-year',
								label: 'Current Year Report',
								description: 'Latest sustainability report',
								icon: FileText,
							},
							{
								id: 'previous-years',
								label: 'Previous Years',
								description: 'Historical reports',
								icon: BookOpen,
							},
							{
								id: 'key-metrics',
								label: 'Key Metrics',
								description: 'Sustainability KPIs',
								icon: BarChart,
							},
						],
					},
					{
						id: 'impact-assessment',
						label: 'Impact Assessment',
						description: 'Environmental impact analysis',
						icon: Activity,
						submenu: [
							{
								id: 'carbon-footprint',
								label: 'Carbon Footprint',
								description: 'CO2 emissions tracking',
								icon: Cloud,
							},
							{
								id: 'water-usage',
								label: 'Water Usage',
								description: 'Water consumption metrics',
								icon: Activity,
							},
							{
								id: 'energy-consumption',
								label: 'Energy Consumption',
								description: 'Energy usage statistics',
								icon: Zap,
							},
						],
					},
				],
			},
			{
				id: 'green-certifications',
				label: 'Green Certifications',
				description: 'Environmental certifications',
				icon: Award,
				submenu: [
					{
						id: 'iso-certifications',
						label: 'ISO Certifications',
						description: 'Environmental ISO standards',
						icon: Award,
						submenu: [
							{
								id: 'iso-14001',
								label: 'ISO 14001',
								description: 'Environmental management',
								icon: Shield,
							},
							{
								id: 'iso-50001',
								label: 'ISO 50001',
								description: 'Energy management',
								icon: Zap,
							},
						],
					},
					{
						id: 'industry-certifications',
						label: 'Industry Certifications',
						description: 'Sector-specific certifications',
						icon: Award,
						submenu: [
							{
								id: 'leed-certification',
								label: 'LEED Certification',
								description: 'Green building certification',
								icon: Building2,
							},
							{
								id: 'energy-star',
								label: 'Energy Star',
								description: 'Energy efficiency rating',
								icon: Zap,
							},
						],
					},
				],
			},
			{
				id: 'community-programs',
				label: 'Community Programs',
				description: 'Environmental community initiatives',
				icon: Users,
				submenu: [
					{
						id: 'education-programs',
						label: 'Education Programs',
						description: 'Environmental education',
						icon: GraduationCap,
						submenu: [
							{
								id: 'school-programs',
								label: 'School Programs',
								description: 'Student education initiatives',
								icon: BookOpen,
							},
							{
								id: 'workshops',
								label: 'Workshops',
								description: 'Sustainability workshops',
								icon: Users,
							},
							{
								id: 'awareness-campaigns',
								label: 'Awareness Campaigns',
								description: 'Public awareness programs',
								icon: MessageSquare,
							},
						],
					},
					{
						id: 'volunteer-opportunities',
						label: 'Volunteer Opportunities',
						description: 'Get involved',
						icon: Heart,
						submenu: [
							{
								id: 'tree-planting',
								label: 'Tree Planting',
								description: 'Reforestation projects',
								icon: Leaf,
							},
							{
								id: 'cleanup-events',
								label: 'Cleanup Events',
								description: 'Community cleanup',
								icon: Users,
							},
							{
								id: 'conservation',
								label: 'Conservation Projects',
								description: 'Wildlife and habitat conservation',
								icon: Heart,
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'investor-relations',
		label: 'Investor Relations',
		description: 'Financial information and investor resources',
		icon: TrendingUp,
		submenu: [
			{
				id: 'financial-information',
				label: 'Financial Information',
				description: 'Company financial data',
				icon: DollarSign,
				submenu: [
					{
						id: 'financial-reports',
						label: 'Financial Reports',
						description: 'Quarterly and annual reports',
						icon: FileText,
						submenu: [
							{
								id: 'quarterly-results',
								label: 'Quarterly Results',
								description: 'Q1, Q2, Q3, Q4 earnings',
								icon: BarChart,
							},
							{
								id: 'annual-reports-investor',
								label: 'Annual Reports',
								description: 'Yearly financial reports',
								icon: FileText,
							},
							{
								id: 'sec-filings',
								label: 'SEC Filings',
								description: 'Regulatory filings',
								icon: FileCheck,
							},
						],
					},
					{
						id: 'stock-information',
						label: 'Stock Information',
						description: 'Share price and performance',
						icon: TrendingUp,
						submenu: [
							{
								id: 'stock-quote',
								label: 'Stock Quote',
								description: 'Real-time stock price',
								icon: Activity,
							},
							{
								id: 'historical-data',
								label: 'Historical Data',
								description: 'Stock price history',
								icon: BarChart,
							},
							{
								id: 'analyst-coverage',
								label: 'Analyst Coverage',
								description: 'Analyst ratings and reports',
								icon: Users,
							},
						],
					},
					{
						id: 'dividends',
						label: 'Dividends',
						description: 'Dividend information',
						icon: DollarSign,
						submenu: [
							{
								id: 'dividend-history',
								label: 'Dividend History',
								description: 'Past dividend payments',
								icon: FileText,
							},
							{
								id: 'dividend-calendar',
								label: 'Dividend Calendar',
								description: 'Upcoming dividend dates',
								icon: Target,
							},
							{
								id: 'reinvestment-plan',
								label: 'Reinvestment Plan',
								description: 'DRIP information',
								icon: TrendingUp,
							},
						],
					},
				],
			},
			{
				id: 'corporate-governance',
				label: 'Corporate Governance',
				description: 'Governance structure and policies',
				icon: Building2,
				submenu: [
					{
						id: 'board-of-directors-investor',
						label: 'Board of Directors',
						description: 'Board composition and committees',
						icon: Users,
						submenu: [
							{
								id: 'board-members',
								label: 'Board Members',
								description: 'Director profiles',
								icon: UserCog,
							},
							{
								id: 'board-committees',
								label: 'Board Committees',
								description: 'Committee structure',
								icon: Grid3x3,
							},
							{
								id: 'meeting-schedule',
								label: 'Meeting Schedule',
								description: 'Board meeting calendar',
								icon: Target,
							},
						],
					},
					{
						id: 'governance-documents',
						label: 'Governance Documents',
						description: 'Corporate policies',
						icon: FileText,
						submenu: [
							{
								id: 'bylaws',
								label: 'Bylaws',
								description: 'Corporate bylaws',
								icon: FileCheck,
							},
							{
								id: 'code-of-conduct',
								label: 'Code of Conduct',
								description: 'Ethics and conduct policy',
								icon: Shield,
							},
							{
								id: 'committee-charters',
								label: 'Committee Charters',
								description: 'Committee guidelines',
								icon: FileText,
							},
						],
					},
				],
			},
			{
				id: 'events-presentations',
				label: 'Events & Presentations',
				description: 'Investor events and materials',
				icon: Video,
				submenu: [
					{
						id: 'earnings-calls',
						label: 'Earnings Calls',
						description: 'Quarterly earnings presentations',
						icon: Phone,
						submenu: [
							{
								id: 'upcoming-calls',
								label: 'Upcoming Calls',
								description: 'Scheduled earnings calls',
								icon: Target,
							},
							{
								id: 'call-transcripts',
								label: 'Call Transcripts',
								description: 'Past call transcripts',
								icon: FileText,
							},
							{
								id: 'webcasts',
								label: 'Webcasts',
								description: 'Live and archived webcasts',
								icon: Video,
							},
						],
					},
					{
						id: 'investor-presentations',
						label: 'Investor Presentations',
						description: 'Presentation materials',
						icon: FileText,
						submenu: [
							{
								id: 'latest-presentation',
								label: 'Latest Presentation',
								description: 'Most recent investor deck',
								icon: FileText,
							},
							{
								id: 'conference-presentations',
								label: 'Conference Presentations',
								description: 'Industry conference materials',
								icon: Building2,
							},
							{
								id: 'roadshow-materials',
								label: 'Roadshow Materials',
								description: 'Investor roadshow decks',
								icon: Plane,
							},
						],
					},
					{
						id: 'investor-events',
						label: 'Investor Events',
						description: 'Upcoming investor events',
						icon: Users,
						submenu: [
							{
								id: 'annual-meeting',
								label: 'Annual Meeting',
								description: 'Shareholder annual meeting',
								icon: Building2,
							},
							{
								id: 'investor-day',
								label: 'Investor Day',
								description: 'Annual investor day event',
								icon: Target,
							},
							{
								id: 'conferences',
								label: 'Conferences',
								description: 'Industry conference participation',
								icon: Users,
							},
						],
					},
				],
			},
			{
				id: 'shareholder-services',
				label: 'Shareholder Services',
				description: 'Services for shareholders',
				icon: Users,
				submenu: [
					{
						id: 'transfer-agent',
						label: 'Transfer Agent',
						description: 'Stock transfer services',
						icon: UserCog,
						submenu: [
							{
								id: 'contact-transfer-agent',
								label: 'Contact Information',
								description: 'Transfer agent details',
								icon: Phone,
							},
							{
								id: 'change-address',
								label: 'Change of Address',
								description: 'Update shareholder address',
								icon: MapPin,
							},
							{
								id: 'lost-certificates',
								label: 'Lost Certificates',
								description: 'Replace lost stock certificates',
								icon: FileText,
							},
						],
					},
					{
						id: 'shareholder-faqs',
						label: 'Shareholder FAQs',
						description: 'Common shareholder questions',
						icon: MessageSquare,
						submenu: [
							{
								id: 'stock-purchase',
								label: 'Stock Purchase',
								description: 'How to buy shares',
								icon: ShoppingCart,
							},
							{
								id: 'dividend-info',
								label: 'Dividend Information',
								description: 'Dividend FAQs',
								icon: DollarSign,
							},
							{
								id: 'tax-information',
								label: 'Tax Information',
								description: 'Tax-related questions',
								icon: Receipt,
							},
						],
					},
				],
			},
			{
				id: 'investor-contacts',
				label: 'Investor Contacts',
				description: 'Contact investor relations',
				icon: Mail,
				submenu: [
					{
						id: 'ir-team',
						label: 'IR Team',
						description: 'Investor relations team',
						icon: Users,
						submenu: [
							{
								id: 'ir-contacts',
								label: 'Contact Information',
								description: 'IR team contact details',
								icon: Phone,
							},
							{
								id: 'email-alerts',
								label: 'Email Alerts',
								description: 'Subscribe to IR updates',
								icon: Mail,
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'contact',
		label: 'Contact',
		description: 'Get in touch with our team',
		icon: Mail,
	},
];
